{% set name = "pandas-dq" %}
{% set version = "1.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_dq-{{ version }}.tar.gz
  sha256: c5ea1ffd3aef56223fa4e3412d0e58d1d5d5d090de2026620689c2149fc11ecf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.21.5
    - pandas >=1.3.5
    - scikit-learn >=0.24.2

    - ipython

test:
  imports:
    - pandas_dq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/pandas_dq
  summary: Clean your data using a scikit-learn transformer in a single line of code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
